[project]
name = "run-esmfold"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fair-esm[esmfold]>=2.0.0",
    "transformers>=4.57.3",
]
