name: esmfold-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.4
  - torchvision
  - torchaudio
  - pip
  - numpy
  - scipy
  - tqdm
  - pip:
      - "transformers>=4.44"
      - accelerate
